djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
]

home/urls.py
from django.urls import path
from . import views

urlpatterns = (
    path("", views.home, name="home"),
    path("index/", views.index, name='index'),
    path("contact/", views.contact, name="contact"),
    path("register/", views.register, name="register"),
)

home/models.py
from django.db import models
import datetime


class ServiceInfo(models.Model):
    happy_clients = models.IntegerField()
    hard_worker = models.IntegerField()
    tie_ups = models.IntegerField()
    support = models.IntegerField()


class Testimonials(models.Model):
    name = models.CharField(max_length=40)
    rating = models.IntegerField()
    message = models.CharField(max_length=200)
    image = models.CharField(max_length=5000, null=True, blank=True)
    occupation = models.CharField(max_length=30, null=True, blank=True)


class Pg(models.Model):
    name = models.CharField(max_length=30)
    image = models.CharField(max_length=5000, null=True, blank=True)


class Contacts(models.Model):
    name = models.CharField(max_length=100)
    mobile = models.IntegerField()
    email = models.EmailField()
    message = models.TextField(blank=True)

    def __str__(self):
        return self.name


class Subscribe(models.Model):
    email = models.EmailField()

    def __str__(self):
        return self.email


class Register(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField(max_length=50)
    phone = models.IntegerField()
    gender = models.CharField(max_length=10)
    room = models.CharField(max_length=10)
    college = models.CharField(max_length=100)
    taxi_service = models.CharField(max_length=10, blank=True, default="No")
    hotel_service = models.CharField(max_length=10, blank=True, default="No")
    checked = models.CharField(max_length=5, blank=True, choices=(("Y", "Yes"), ("N", "No")))
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)


class Test(models.Model):
    name = models.CharField(max_length=40)
    college = models.CharField(max_length=50)

home/forms.py
from django.forms import ModelForm
from .models import Contacts, Subscribe, Register, Test


class ContactForm(ModelForm):
    class Meta:
        model = Contacts
        fields = '__all__'


class SubscribeForm(ModelForm):
    class Meta:
        model = Subscribe
        fields = '__all__'


class RegisterForm(ModelForm):
    class Meta:
        model = Register
        fields = '__all__'


class TestForm(ModelForm):
    class Meta:
        model = Test
        fields = '__all__'

home/views.py
from django.shortcuts import render
from .models import *
from .forms import ContactForm, SubscribeForm, RegisterForm, TestForm
from django.http import HttpResponse, HttpResponseRedirect
from django.conf import settings
from django.core.mail import send_mail


def home(request):
    pg = Pg.objects.all()
    service_info = ServiceInfo.objects.all()
    testimonials = Testimonials.objects.all()
    for t in testimonials:
        z = []
        z.extend(iter(range(1, t.rating + 1)))
        t.rating = z
    if request.method == "POST":
        subscribe_form = SubscribeForm(request.POST)
        contact_form = ContactForm(request.POST)
        if contact_form.is_valid():
            contact_form.save()
            return True
        elif subscribe_form.is_valid():
            subscribe_form.save()
            return True
        else:
            return HttpResponse("Please Retry")
    context = {'pg': pg, 'service_info': service_info, 'testimonials': testimonials}
    return render(request, "home/home.html", context)


def contact(request):
    contact_form = ContactForm(request.POST)
    if request.method == "POST":
        if contact_form.is_valid():
            contact_form.save()
            send_contact_email(contact_form)
            return HttpResponse("It works")
        else:
            return HttpResponse("Please Retry")
    context = {'contactForm': contact_form}
    return render(request, "home/contact.html", context)


def send_contact_email(contact_form):
    email_subject = f'New contact: {contact_form.cleaned_data["name"]}: {contact_form.cleaned_data["mobile"]}'
    email_message = f'Name: {contact_form.cleaned_data["name"]} \nMessage: {contact_form.cleaned_data["message"]}'
    send_mail(email_subject, email_message, settings.CONTACT_EMAIL, ['srivardhan.singh.rathore@gmail.com'],
              fail_silently=False)
    print("Sent mail")


def register(request):
    register_form = RegisterForm(request.POST)
    if request.method == 'POST':
        if register_form.is_valid():
            register_form.save()
        return HttpResponse("It works")
    return render(request, "home/register.html")


def index(request):
    pg = Pg.objects.all()
    service_info = ServiceInfo.objects.all()
    testimonials = Testimonials.objects.all()
    for t in testimonials:
        z = []
        z.extend(iter(range(1, t.rating + 1)))
        t.rating = z
        print(z)
    if request.method == 'POST':
        subscribe_form = SubscribeForm(request.POST)
        contact_form = ContactForm(request.POST)
        if contact_form.is_valid():
            contact_form.save()
            return HttpResponse("Success")
        elif subscribe_form.is_valid():
            subscribe_form.save()
            return HttpResponse("Success")
        else:
            return HttpResponse("Please Retry")

    context = {'pg': pg, 'service_info': service_info, 'testimonials': testimonials}
    return render(request, "home/index.html", context)

templates/home/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>{% block title %} {% endblock %} - ShelterSearch</title>
  <meta content="" name="description">

  <meta content="" name="keywords">

  <!-- Bootstrap CSS -->
{#  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">#}

  <link href="{% static 'assets/img/logo4.png' %}" rel="icon">
  <link href="{% static 'assets/img/logo4.png' %}" rel="apple-touch-icon">

  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <link href="{% static 'assets/vendor/aos/aos.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

  <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">

</head>

<body>

{% include "home/header.html" %}
{% block content %}
{% endblock %}
{% include "home/sections/footer-section.html" %}

    <!-- Vendor JS Files -->
    <script src="{% static 'assets/vendor/purecounter/purecounter_vanilla.js' %}"></script>
    <script src="{% static 'assets/vendor/aos/aos.js' %}"></script>
    <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
    <script src="{% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
    <script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
    <script src="{% static 'assets/vendor/php-email-form/validate1.js' %}"></script>

    <!-- Template Main JS File -->
    <script src="{% static 'assets/js/main.js' %}"></script>
</body>

</html>

templates/home/contact.html
{% extends 'home/base.html' %}


{% block title %}
    Contact
{% endblock %}


{% block content %}
    <br><br>
    {% include 'home/sections/contact-section.html' with posts=postdata %}

{% endblock %}

templates/home/footer.html
{% load static %}

<!-- ======= Footer ======= -->
  <footer id="footer" class="footer">

    <div class="footer-top">
      <div class="container">
        <div class="row gy-4">
          <div class="col-lg-5 col-md-12 footer-info">
            <a href="{% url 'home' %}#hero" class="logo d-flex align-items-center">
              <img src="{%  static 'assets/img/logo4.png' %}" alt="">
              <span>ShelterSearch</span>
            </a>
            <p>Cras fermentum odio eu feugiat lide par naso tierra. Justo eget nada terra videa magna derita valies darta donna mare fermentum iaculis eu non diam phasellus.</p>
            <div class="social-links mt-3">
              <a href="#" class="twitter"><i class="bi bi-twitter"></i></a>
              <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
              <a href="#" class="instagram"><i class="bi bi-instagram"></i></a>
              <a href="#" class="linkedin"><i class="bi bi-linkedin"></i></a>
            </div>
          </div>

          <div class="col-lg-2 col-6 footer-links">
            <h4>Useful Links</h4>
            <ul>
              <li><i class="bi bi-chevron-right"></i> <a href="{% url 'home' %}">Home</a></li>
              <li><i class="bi bi-chevron-right"></i> <a href="{% url 'home' %}#about">About us</a></li>
              <li><i class="bi bi-chevron-right"></i> <a href="{% url 'home' %}#values">Services</a></li>
              <li><i class="bi bi-chevron-right"></i> <a href="#">Terms of service</a></li>
              <li><i class="bi bi-chevron-right"></i> <a href="{% url 'contact' %}#contact">Contact</a></li>
            </ul>
          </div>

          <div class="col-lg-2 col-6 footer-links">
            <h4>Our Services</h4>
            <ul>
              <li><i class="bi bi-chevron-right"></i> <a href="#">Web Design</a></li>
              <li><i class="bi bi-chevron-right"></i> <a href="#">Web Development</a></li>
              <li><i class="bi bi-chevron-right"></i> <a href="#">Product Management</a></li>
              <li><i class="bi bi-chevron-right"></i> <a href="#">Marketing</a></li>
              <li><i class="bi bi-chevron-right"></i> <a href="#">Graphic Design</a></li>
            </ul>
          </div>

          <div class="col-lg-3 col-md-12 footer-contact text-center text-md-start">
            <h4>Contact Us</h4>
            <p>
              CMS, Lalbagh<br>Bengaluru, Karnataka 560029 <br><br>
              <strong>Phone:</strong> +91 87618 10611<br>
              <strong>Email:</strong> info@sheltersearch.in<br>
            </p>

          </div>

        </div>
      </div>
    </div>

    <div class="container">
      <div class="copyright">
        &copy; Copyright <strong><span>ShelterSearch</span></strong>. All Rights Reserved
      </div>
{#      <div class="credits">#}
{#        Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>#}
{#      </div>#}
    </div>
  </footer>
<!-- End Footer -->

templates/home/header.html
{% load  static %}
<!-- ======= Header ======= -->
  <header id="header" class="header fixed-top">
    <div class="container-fluid container-xl d-flex align-items-center justify-content-between">

      <a href="{% url 'home' %}#hero" class="logo d-flex align-items-center">
        <img src="{% static 'assets/img/logo4.png' %}" alt="">
        <span>ShelterSearch</span>
      </a>
        <!-- ====== Navbar ====== -->
      <nav id="navbar" class="navbar">
        <ul>
          <li><a class="nav-link scrollto active" href="{% url 'home' %}#hero">Home</a></li>
          <li><a class="nav-link scrollto" href="{% url 'home' %}#about">About</a></li>
          <li><a class="nav-link scrollto" href="{% url 'home' %}#values">Services</a></li>
{#          <li><a class="nav-link scrollto" href="#portfolio">Portfolio</a></li>#}
{#          <li><a class="nav-link scrollto" href="#team">Team</a></li>#}
{#          <li><a href="blog.html">Blog</a></li>#}
{#          <li class="dropdown"><a href="#"><span>Drop Down</span> <i class="bi bi-chevron-down"></i></a>#}
{#            <ul>#}
{#              <li><a href="#">Drop Down 1</a></li>#}
{#              <li class="dropdown"><a href="#"><span>Deep Drop Down</span> <i class="bi bi-chevron-right"></i></a>#}
{#                <ul>#}
{#                  <li><a href="#">Deep Drop Down 1</a></li>#}
{#                  <li><a href="#">Deep Drop Down 2</a></li>#}
{#                  <li><a href="#">Deep Drop Down 3</a></li>#}
{#                  <li><a href="#">Deep Drop Down 4</a></li>#}
{#                  <li><a href="#">Deep Drop Down 5</a></li>#}
{#                </ul>#}
{#              </li>#}
{#              <li><a href="#">Drop Down 2</a></li>#}
{#              <li><a href="#">Drop Down 3</a></li>#}
{#              <li><a href="#">Drop Down 4</a></li>#}
{#            </ul>#}
{#          </li>#}
          <li><a class="nav-link scrollto" href="{% url 'contact' %}">Contact</a></li>
          <li><a class="getstarted scrollto" href="{% url 'register' %}#about">Register</a></li>
        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav>
        <!-- ======.navbar ====== -->

    </div>
  </header>
<!-- End Header -->

templates/home/register.html
{% extends 'home/base.html' %}
{% load static %}


{% block title %}
    Registration
{% endblock %}

{% block content %}
    <br><br>
    {% include "home/sections/register-section.html" with posts=postdata %}
{% endblock %}h

templates/home/sections/contact-section.html
{% load static %}
    <!-- ======= Contact Section ======= -->
    <section id="contact" class="contact">

      <div class="container" data-aos="fade-up">

        <header class="section-header">
          <h2>Contact</h2>
          <p>Contact Us</p>
        </header>

        <div class="row gy-4">

          <div class="col-lg-6">

            <div class="row gy-4">
              <div class="col-md-6">
                <div class="info-box">
                  <i class="bi bi-geo-alt"></i>
                  <h3>Address</h3>
                  <p>CMS, Lalbagh<br>Bengaluru, Karnataka 560029</p>
                </div>
              </div>
              <div class="col-md-6">
                <div class="info-box">
                  <i class="bi bi-telephone"></i>
                  <h3>Call Us</h3>
                  <p>+91 87618 10611<br>+91 63626 31737</p>
                </div>
              </div>
              <div class="col-md-6">
                <div class="info-box">
                  <i class="bi bi-envelope"></i>
                  <h3>Email Us</h3>
                  <p>info@sheltersearch.in<br>contact@sheltersearch.in</p>
                </div>
              </div>
              <div class="col-md-6">
                <div class="info-box">
                  <i class="bi bi-clock"></i>
                  <h3>Open Hours</h3>
                  <p>Monday - Saturday<br>9:00AM - 9:00PM</p>
                </div>
              </div>
            </div>

          </div>

          <div class="col-lg-6">
            <form action="{% url 'contact' %}" method="post" role="form" class="php-email-form">
                <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}">
              <div class="row gy-4">
                <div class="col-md-6">
                  <input type="text" name="name" class="form-control" placeholder="Your Name" required>
                </div>

                <div class="col-md-6 ">
                  <input type="email" class="form-control" name="email" placeholder="Your Email" required>
                </div>

                <div class="col-md-12" id="number">
                  <input type="tel" class="form-control" name="mobile" placeholder="Phone" maxlength="10" required>
                </div>
                <div class="form-group mt-3">
                <textarea class="form-control" name="message" rows="5" placeholder="Message" required></textarea>
                </div>
                <div class="col-md-12 text-center">
                  <div class="loading">Loading</div>
                  <div class="error-message"></div>
                  <div class="sent-message">Your message has been sent. Thank you!</div>

                  <button type="submit" value="Submit">Send Message</button>
                </div>

              </div>
            </form>

          </div>

        </div>

      </div>

    </section>
    <!-- End Contact Section -->

templates/home/sections/footer-section.html
{% load static %}

<!-- ======= Footer ======= -->
  <footer id="footer" class="footer">

    <div class="footer-top">
      <div class="container">
        <div class="row gy-4">
          <div class="col-lg-5 col-md-12 footer-info">
            <a href="{% url 'home' %}#hero" class="logo d-flex align-items-center">
              <img src="{%  static 'assets/img/logo4.png' %}" alt="">
              <span>ShelterSearch</span>
            </a>
            <p>We help you find the best accommodation, so you don't face the hassle.</p>
            <div class="social-links mt-3">
              <a href="#" class="twitter"><i class="bi bi-twitter"></i></a>
              <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
              <a href="#" class="instagram"><i class="bi bi-instagram"></i></a>
              <a href="#" class="linkedin"><i class="bi bi-linkedin"></i></a>
            </div>
          </div>

          <div class="col-lg-2 col-6 footer-links">
            <h4>Useful Links</h4>
            <ul>
              <li><i class="bi bi-chevron-right"></i> <a href="{% url 'home' %}">Home</a></li>
              <li><i class="bi bi-chevron-right"></i> <a href="{% url 'home' %}#about">About us</a></li>
              <li><i class="bi bi-chevron-right"></i> <a href="{% url 'home' %}#values">Services</a></li>
              <li><i class="bi bi-chevron-right"></i> <a href="#">Terms of service</a></li>
              <li><i class="bi bi-chevron-right"></i> <a href="{% url 'contact' %}">Contact</a></li>
            </ul>
          </div>

          <div class="col-lg-2 col-6 footer-links">
            <h4>Our Services</h4>
            <ul>
              <li><i class="bi bi-chevron-right"></i> <a href="{% url 'home' %}#values">Accommodation</a></li>
              <li><i class="bi bi-chevron-right"></i> <a href="{% url 'home' %}#values">Taxi Service</a></li>
              <li><i class="bi bi-chevron-right"></i> <a href="{% url 'home' %}#values">Hotel Booking</a></li>
{#              <li><i class="bi bi-chevron-right"></i> <a href="#">Marketing</a></li>#}
{#              <li><i class="bi bi-chevron-right"></i> <a href="#">Graphic Design</a></li>#}
            </ul>
          </div>

          <div class="col-lg-3 col-md-12 footer-contact text-center text-md-start">
            <h4>Contact Us</h4>
            <p>
              CMS, Lalbagh<br>Bengaluru, Karnataka 560029 <br><br>
              <strong>Phone:</strong><a href="tel:+918761810611"> +91 87618 10611 </a><br>
              <strong>Email:</strong><a href="mailto:info@sheltersearch.in"> info@sheltersearch.in</a><br>
            </p>

          </div>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="copyright">
        &copy; Copyright <strong><span>ShelterSearch</span></strong>. All Rights Reserved
      </div>
{#      <div class="credits">#}
{#        Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>#}
{#      </div>#}
    </div>
  </footer>
<!-- End Footer -->

templates/home/sections/register-section.html
{% load static %}
    <!-- ======= Contact Section ======= -->
    <section id="contact" class="contact">

      <div class="container" data-aos="fade-up">

        <header class="section-header">
          <h2>ShelterSearch</h2>
          <p>Register</p>
        </header>
        <div class="row gy-4">

          <div class="col-lg-12">
            <form action="{% url 'register' %}" method="post" role="form" class="php-email-form">
                <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}">
              <div class="row gy-4">
                <div class="col-md-6">
                    <input type="text" name="name" class="form-control" placeholder="Your Name" required>
                </div>

                <div class="col-md-6 ">
                    <input type="email" name="email" class="form-control" placeholder="Your Email" required>
                </div>

                <div class="col-md-6">
                    <input type="tel" name="phone" class="form-control" placeholder="Phone" maxlength="10" required>
                </div>

                <div class="col-md-6">
                    <select name="gender" class="form-control" required>
                        <option value disabled selected hidden>Gender</option>
                        <option value="M">Male</option>
                        <option value="F">Female</option>
                        <option value="O">Custom</option>
                    </select>
                </div>
                <div class="col-md-6">
                    <select name="room" class="form-control" required >
                        <option value disabled selected hidden>Room Occupancy</option>
                        <option value="S">Single</option>
                        <option value="D">Double</option>
                        <option value="T">Triple</option>
                    </select>
                </div>
                <div class="col-md-6">
                  <input type="text" name="college" class="form-control" placeholder="Your College Name" required>
                </div>
{#                <div class="col-md-6">#}
{#                    <input type="checkbox" value="Yes" name="taxi_service" id="id_taxi_service">#}
{#                    <label class="vCheckboxLabel" id="id_taxi_service">Taxi Service</label>#}
{#                </div>#}
                  <div class="col-md-12">
                      <label class="form-label">When you arrive at Bangalore, would to like to use our: </label>
                  </div>

                <div class="col-md-6">
                  <input class="form-check-input" type="checkbox" value="Yes" name="taxi_service" id="id_taxi_service">
                  <label class="form-label" for="flexCheckDefault">
                    Taxi Service
                  </label>
                </div>
                <div class="col-md-6">
                    <input type="checkbox" class="form-check-input" value="Yes" name="hotel_service" id="id_hotel_service">
                    <label class="vCheckboxLabel" id="id_hotel_service">Hotel Service</label>
                </div>

                <div class="col-md-12 text-center">
                  <div class="loading">Loading</div>
                  <div class="error-message"></div>
                  <div class="sent-message">Your message has been sent. Thank you!</div>

                  <button type="submit" value="Submit">Send Message</button>
                </div>

              </div>
            </form>

          </div>

        </div>

      </div>

    </section>
    <!-- End Contact Section -->

templates/home/sections/test.html
<script src="https://unpkg.com/htmx.org@1.8.5" integrity="sha384-7aHh9lqPYGYZ7sTHvzP1t3BAfLhYSTy9ArHdP3Xsr9/3TlGurYgcPBoFmXX2TX/w" crossorigin="anonymous"></script>

<button hx-post="/clicked"
    hx-trigger="click"
    hx-target="#parent-div"
    hx-swap="outerHTML">
    Click Me!
</button>

<div hx-put="/messages">
    Put the messages
</div>